### ISSUE TITLE
Sync two adguards using AdGuardHome sync , need port 3000

### ISSUE THREAD

**Issue by warlordattack** [hassio-addons/addon-adguard-home#517]
Hello i would like sync hassio addon adguard with an other adguard instance on an other VM.

AdGuardHome sync : 
https://github.com/bakito/adguardhome-sync

This requires to be able to acces adguard hassio addon port 3000

Is it possible to publish this port 3000 with the addon please ?
If yes how ?
I did not find this option in the addon options.

Best regards :)

**Comment by warlordattack** [comment]
Solved : 

Home Assistant > Adguard Addon > configuration > disable SSL > enable hiden ports > web interface = 9980 > restart addon
Then you can connect into HASS adguard GUI : <homeassistant IP>:9980 (home assistant user/password)

Then run adguard sync like this : 
```
version: "2.1"
services:

  srv_adguard_sync:
    #user: ${PUID}:${PGID}
    command: run --config /config/adguardhome-sync.yaml
    container_name: ${C_ADS}
    image: ${C_ADS_IMG}
    restart: ${C_ALL_RESTART}
    hostname: ${C_ADS_HOST}
    ports:
      - ${C_ADS_8080}:8080
    volumes:
      #- ${REP_APPDATA}/${C_AD}/sync/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
      - ${REP_APPDATA}/${C_AD}/sync/:/config/
    environment:
      # adguard principal
      - ORIGIN_URL=http://${C_HASS_IP}:9980/
      - ORIGIN_USERNAME=${C_HASS_U}
      - ORIGIN_PASSWORD=${C_HASS_P}
      # adguard copie 1
      - REPLICA_URL=http://${C_AD_IP_MVL}/ 
      - REPLICA_USERNAME=${C_AD_U} 
      - REPLICA_PASSWORD=${C_AD_P} 
      # adguard copie 2
      - REPLICA1_URL=http://${C_AD_IP_MVL_2}/
      - REPLICA1_USERNAME=${C_AD_U}
      - REPLICA1_PASSWORD=${C_AD_P}
      - CRON=*/1 * * * * # run every 1 minute
      - RUN_ON_START=true
    networks:
      mvlan:
        ipv4_address: ${C_ADS_IP_MVL}
networks: 
  mvlan: 
    external: true

```

and run two other instances of adguard like this : 

```
version: "2.1"
services:

  srv_adguard: # https://hub.docker.com/r/adguard/adguardhome
    container_name: ${C_AD}
    #user: ${PUID}:${PGID}
    image: ${C_AD_IMG}
    restart: ${C_ALL_RESTART}
    hostname: ${C_AD_HOST}
#    ports: # en MACVLAN tous les ports sont accessibles
#      # admin panel
#      - ${C_AD_80}:80/tcp
#      - ${C_AD_443}:443/tcp
#      - ${C_AD_443}:443/udp
#      # DHCP server
#      - ${C_AD_67}:67/udp
#      - ${C_AD_68}:68/tcp
#      - ${C_AD_68}:68/udp
#      # plain DNS
#      - ${C_AD_53}:53/tcp     
#      - ${C_AD_53}:53/udp
#      # DNS-over-TLS server
#      - ${C_AD_853}:853/tcp
#      # HTTPS/DNS-over-HTTPS server
#      - ${C_AD_3000}:3000/tcp
#      # DNS-over-QUIC serve
#      - ${C_AD_784}:784/udp
#      - ${C_AD_853}:853/udp
#      - ${C_AD_8853}:8853/udp
#      # DNSCrypt server
#      - ${C_AD_5443}:5443/tcp
#      - ${C_AD_5443}:5443/udp
    volumes:
      - ${REP_APPDATA}/${C_AD}/conf:/opt/adguardhome/conf:rw
      - ${REP_APPDATA}/${C_AD}/work:/opt/adguardhome/work:rw
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    labels:
      - "com.centurylinklabs.watchtower.enable=${WATCHTOWER_LABEL_ENABLE}"
    networks:
      mvlan:
        ipv4_address: ${C_AD_IP_MVL}
networks: 
  mvlan: 
    external: true
```

My macvlan config for adguard and adguard sync : 
```
    echo "---- +MVLAN ----"
    # ip-range(29) : 7 adresses 192.168.50.200-207
    # parent : enp6s18 (ubuntu) / ens18 (rocky) / eth0 (other)
    podman network create -d macvlan \
    --gateway=192.168.50.1 \
    --subnet=192.168.50.0/24 \
    --ip-range=192.168.50.200/29 \
    --opt parent=ens18 \
    mvlan
    #--opt com.docker.network.driver.mtu=9216 \
```
