### ISSUE TITLE
Feature Request: Expose "Blocked Services" as an HA service

### ISSUE THREAD

**Issue by jeffehobbs** [hassio-addons/addon-adguard-home#87]
# Problem/Motivation

AdGuard has proven to be a wonderful home network management tool as I try to keep my child focused on distance learning across devices. At the beginning of the school day, I turn off Discord, YouTube, Instagram and Twitter in order to focus on schoolwork. When homework is done, I will turn the services back on. Works great.

The problem is, this is a highly manual process. I have to go into Home Assistant, into Ad Guard, into Blocked Services, select the services to turn on and off and hit save.

## Proposed changes

What would be great is if these blocked services could be exposed in the AdGuard API and subsequently controlled via Home Assistant. Then I could set up automations that would enable and disable services 

I did a small amount of research around the AdGuard API and the adguardhome python package but could not confirm or deny how difficult this would be, or what the blockers are. I'd be interested in any data points here or any thoughts in general. Thanks for listening!

**Comment by AlecRust** [comment]
I too am after this feature. I have a workaround for you in the meantime though. You can call a [service](https://www.home-assistant.io/integrations/adguard/#services) to enable/disable a particular filter:

```yaml
automation:
  - alias: 'Block social networks in morning'
    trigger:
      platform: time
      at: "08:00"
    action:
      service: adguard.enable_url
      data:
        # This seems to be the filter AdGuard Home uses for "blocked services"
        url: "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt"
```
